# Generated by Django 2.2 on 2020-10-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories4LiveTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='News', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories4Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='Drama', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories4TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='Science', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(default='English', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowName', models.CharField(default='channel', max_length=30)),
                ('posterLocation', models.CharField(default='/static/images/aajtak.png', max_length=100)),
                ('Ep1', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep2', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep3', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep4', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep5', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep6', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep7', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep8', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep9', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep10', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Ep11', models.CharField(blank=True, default='https://cdn.plyr.io/static/blank.mp4', max_length=500)),
                ('Language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Language')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Categories4TvShow')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(default='channel', max_length=30)),
                ('posterLocation', models.CharField(default='/static/images/aajtak.png', max_length=100)),
                ('MovieURL', models.CharField(default='https://aajtakhdlive-amd.akamaized.net/hls/live/2014415-b/aajtakhd/aajtakhdlive/aajtakhd_5/chunklist.m3u8', max_length=500)),
                ('Language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Language')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Categories4Movie')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(default='channel', max_length=30)),
                ('posterLocation', models.CharField(default='/static/images/aajtak.png', max_length=100)),
                ('channelURL', models.CharField(default='https://aajtakhdlive-amd.akamaized.net/hls/live/2014415-b/aajtakhd/aajtakhdlive/aajtakhd_5/chunklist.m3u8', max_length=500)),
                ('Language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Language')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Categories4LiveTv')),
            ],
        ),
        migrations.CreateModel(
            name='FrontView_LiveTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LiveTV', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.LiveTV')),
            ],
        ),
    ]
