# Generated by Django 2.2 on 2020-10-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontView_TVSHOWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TvShow', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.TvShow')),
            ],
        ),
        migrations.CreateModel(
            name='FrontView_MOVIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.Movie')),
            ],
        ),
    ]
