# Generated by Django 2.2 on 2020-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0003_auto_20201006_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posterLocation',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
