# Generated by Django 2.2 on 2020-10-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0007_auto_20201006_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='posterLocation',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='posterLocation',
            new_name='poster',
        ),
    ]
