# Generated by Django 2.2 on 2020-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0008_auto_20201006_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep1',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep10',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep11',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep2',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep3',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep4',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep5',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep6',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep7',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep8',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='Ep9',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='showURL',
            field=models.CharField(default='https://cdn.plyr.io/static/blank.mp4', max_length=500),
        ),
    ]
