# Generated by Django 2.2 on 2020-10-11 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0010_auto_20201009_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
            ],
        ),
    ]
