# Generated by Django 2.2 on 2020-10-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0011_tvshowseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='showURL',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TvShowEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ep1', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep2', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep3', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep4', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep5', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep6', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep7', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep8', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep9', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep10', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep11', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep12', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep13', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep14', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep15', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep16', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep17', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep18', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep19', models.CharField(blank=True, max_length=500, null=True)),
                ('Ep20', models.CharField(blank=True, max_length=500, null=True)),
                ('SelectSeason', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.TvShowSeason')),
                ('SelectShow', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vikstreamz.TvShow')),
            ],
        ),
    ]
