# Generated by Django 2.2 on 2020-10-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0012_auto_20201011_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep1',
            new_name='Ep10URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep10',
            new_name='Ep11URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep11',
            new_name='Ep12URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep12',
            new_name='Ep13URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep13',
            new_name='Ep14URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep14',
            new_name='Ep15URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep15',
            new_name='Ep16URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep16',
            new_name='Ep17URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep17',
            new_name='Ep18URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep18',
            new_name='Ep19URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep19',
            new_name='Ep1URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep2',
            new_name='Ep20URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep20',
            new_name='Ep2URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep3',
            new_name='Ep3URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep4',
            new_name='Ep4URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep5',
            new_name='Ep5URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep6',
            new_name='Ep6URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep7',
            new_name='Ep7URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep8',
            new_name='Ep8URL',
        ),
        migrations.RenameField(
            model_name='tvshowepisode',
            old_name='Ep9',
            new_name='Ep9URL',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='showURL',
        ),
    ]
