# Generated by Django 2.2 on 2020-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0013_auto_20201011_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep10URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep11URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep12URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep13URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep14URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep15URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep16URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep17URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep18URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep19URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep1URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep20URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep2URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep3URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep4URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep5URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep6URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep7URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep8URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='Ep9URL',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
