# Generated by Django 2.2 on 2020-10-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0014_auto_20201011_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='ratings',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
