# Generated by Django 2.2 on 2020-10-21 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0015_tvshow_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='ratings',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
