# Generated by Django 2.2 on 2020-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikstreamz', '0017_tvshow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(blank=True, default='Show description', max_length=5000),
        ),
    ]
